### ISSUE TITLE
Applying for membership

### ISSUE THREAD

**Issue by bzz** [DIYbiosphere/sphere.dir#108]
My name is Alexander and I'm a software engineer living in Seoul, South Korea and one of the co-organizers of https://github.com/SeoulTech

I'd love to get involved more in DIYbio myself, as well as help promoting and developing it here, in Asia, especially in Korea.

**Comment by sabgaby** [comment]
That's amazing!! I am glad you are interested in the project! You can always send me a PM on Gitter or Slack if you have any questions!
