### ISSUE TITLE
Googling DIYbiosphere

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere.dir#113]
So... I don't know just how much we can do about it...
But googling "DIYbiosphere" returns no results.. its better if I google "DIYbiosphere database".. but it still does not return the website sphere.diybio.org

Is there anything we can do about this? This seems very crucial.. It might just resolve eventually as people start using and googling the site.. idk what do you think?

**Comment by sabgaby** [comment]
This would be resolved once the website gets more hits.. nothing to do about it now
