### ISSUE TITLE
Slackin invite not working!

### ISSUE THREAD

**Issue by ahuacatl** [DIYbiosphere/sphere.dir#123]
The slackin invite is not working. It gives the following error. Found no solutions online
![slackin not working](https://cloud.githubusercontent.com/assets/18292357/16806474/ea094ab8-4914-11e6-9049-2e1dd55495c3.gif)

**Comment by ahuacatl** [comment]
Here is the [issue open](https://github.com/rauchg/slackin/issues/79) in the Slackin Github

**Comment by sabgaby** [comment]
It has been fixed
