### ISSUE TITLE
Define "host" field in Lab

### ISSUE THREAD

**Issue by jasonbobe** [DIYbiosphere/sphere.dir#129]
I'm not sure what "host" means. Define?

**Comment by ahuacatl** [comment]
host/parent institution or organization.. 
Many DIYbio labs are hosted by a hackerspace for example

**Comment by ahuacatl** [comment]
I made a quick [Gist](https://gist.github.com/ahuacatl/954444c7f15a27190b0fd52e0021a58c) for explaining the front matter.. I am working this week and the next on cleaning up the documentation

**Comment by sabgaby** [comment]
Tooltips will be added to the infobox for when you hover over the field icons. They are already implemented. A bit more information on each could be useful and maybe an additional ℹ️  button for more information on the definition on the fields

![tooltip](https://cloud.githubusercontent.com/assets/5911330/17925756/813d182a-69ee-11e6-9d81-0d028fd20513.gif)
