### ISSUE TITLE
Implement estimated reading time in Support section

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere.dir#14]
So I was thinking that adding an estimated reading time (i.e. 2 min read) might encourage viewers to actually _read_ the guides. I saw some blogs on how to do it on Jekyll:
[Jekyll reading time without plugins](http://carlosbecker.com/posts/jekyll-reading-time-without-plugins)
[reading time](https://andytaylor.me/2013/04/07/reading-time/)
[simple reading speed estimate in jekyll](https://www.jacobtomlinson.co.uk/jekyll/2015/02/24/simple-reading-speed-estimate-in-jekyll/)

No rush on this!

**Comment by ahuacatl** [comment]
Done and implemented beautifully!
