### ISSUE TITLE
Creating a or "communal" GitHub account

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere.dir#43]
Someone suggested to me that as users may be deterred to participate since they have to have a GitHub account, that maybe we could create a communal account with a shared password, so that anyone could enter and create changes from that account. A project maintainer would have to be the sole owner of the recovery email in case a troll changes the password.

This might be too complicated, but it was just a suggestion

**Comment by kaythaney** [comment]
One suggestion (to limit the potential for abuse in a shared account + password) would be to have folks create their own account, then set up a team in GitHub that gives them all access rights. We also have this friendly GitHub intro (using the web interface) which may help. https://mozillascience.github.io/working-open-workshop/github_for_collaboration/
