### ISSUE TITLE
Keywords in infobox repeat commas

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere.dir#78]
As I input keywords in the front matter of an entry, I separate them with commas. however, the commas appear double in the infobox. Maybe I don't know how to separate them in the infobox
![screen shot 2016-06-13 at 23 15 35](https://cloud.githubusercontent.com/assets/5911330/16037941/108850d4-3223-11e6-9f3e-6c390ef92cf9.png)

**Comment by valterlima** [comment]
Hello Gabriela!

It looks like this is the desired way tags from github pages works. The line of code is right [here](https://github.com/DIYbiosphere/sphere.dir/blob/54b9da170b28dd0112f80fa103ae5197b464b383/_layouts/entry.html#L70):
`<i class="octicon octicon-tag"></i> {{ page.tags | array_to_sentence_string }}`

The `array_to_sentence_string` thing works exactly like described [here](http://www.rubydoc.info/gems/spreefinery_themes/Liquid/Filters:array_to_sentence_string): _Join an array of things into a string by separating with commas and the word “and” for the last one._

You should try using the tags on your page separated by spaces, like this: `tags: database open-source`

**Comment by sabgaby** [comment]
Hey @valterlima! thanks for the response! But I have a question, what if I want to use a tag with two words, such as "environmental monitoring"... having a dash between them doesn't make sense.

**Comment by valterlima** [comment]
I'm not sure as I'm unable to test it right now, but I think you can use like this: 
`tags: ['The is a tag', 'This is another tag']`

**Comment by cube5** [comment]
Right, this works too:
```
tags:
  - database
  - open source
  - some other tag
```
